### ISSUE TITLE
Extended GCD | Maths | Python

### ISSUE THREAD

**Issue by chrismilson** [Py-Contributors/AlgorithmsAndDataStructure#578] opened 2020-10-05 02:52 UTC
## **Extended GCD**

May be considered a clone of #42, but (depending on the implementation) likely not.

The greatest common denominator is an important algorithm. When given two positive integers `a` and `b`, it calculates the greatest positive integer `g` such that `g` divides both `a` and `b`. The extended gcd algorithm also calculates two other numbers `u` and `v` such that `ua + vb = g`, while not increasing the time complexity of the algorithm.

**what will change** -

I will add a new algorithm to `Python/Algorithms/Maths/` that implements `extendedGcd`.

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

**Comment by chrismilson** [comment] 2020-10-05 02:52
I would like to be assigned to this.

**Comment by ExpressHermes** [comment] 2020-10-05 07:20
@chrismilson You can do it as an improvement of #42. When the PR for #42 is merged, you can add this implementation in the seperate function inside #42 changes.

**Comment by shubham5351** [comment] 2020-10-05 07:31
As there is seperate procedure for the improvement of the code so this  issue is duplicate of #42 so I'm closing this issue.

**Closed as completed by shubham5351** 2020-10-05 07:31 UTC
Labels: good first issue, hacktoberfest
