### ISSUE TITLE
0-1 Knapsack Problem | Dynamic Programming | Python

### ISSUE THREAD

**Issue by tarundhiraj** [Py-Contributors/AlgorithmsAndDataStructure#467] opened 2020-10-02 04:39 UTC
## **`Title`** - 0-1 Knapsack Problem in Python

**what will change** -
implementation of solution in python
### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by tarundhiraj** [comment] 2020-10-02 04:39
I would like to work on this issue. Please assign this issue to me.  Thanks.

**Comment by tejasbirsingh** [comment] 2020-10-02 04:56
I would like to work on 0-1 Knapsack Problem . I will write clean code and add proper explanation . Thanks

**Comment by adityalata** [comment] 2020-10-02 07:21
Would like to submit a Pull Request, can you please assign this issue to me....

**Comment by ExpressHermes** [comment] 2020-10-03 08:58
Duplicate of #149

**Closed as completed by ExpressHermes** 2020-10-03 08:58 UTC
