### ISSUE TITLE
Pattern Searching using Rabin Karp's Algorithm | Algorithms | Python

### ISSUE THREAD

**Issue by debashis05** [Py-Contributors/AlgorithmsAndDataStructure#491] opened 2020-10-02 06:43 UTC
## **`Title`** - Pattern Searching using Rabin Karp's Algorithm

**what will change** - Added new code

### Type of Issue - 

Please add/delete options that are not relevant.

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by rohangawhade** [comment] 2020-10-02 07:03
I would like to work on this.

**Comment by ExpressHermes** [comment] 2020-10-02 16:38
Duplicate of #41

**Closed as completed** 2020-10-02 16:38 UTC
Labels: duplicate issue
