### ISSUE TITLE
Floyd's Cycle Detection Algorithm | Algorithms | Python

### ISSUE THREAD

**Issue by rapunzel127** [Py-Contributors/AlgorithmsAndDataStructure#677] opened 2020-10-09 16:09 UTC
## **`Floyd's Cycle Detection Algorithm`** -

**what will change** - Implementation of Floyd's Cycle Detection Algorithm in Python

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by rapunzel127** [comment] 2020-10-09 16:09
I would like to work on this issue.Please assign me.

**Comment by codeperfectplus** [comment] 2020-10-11 10:03
Duplicate of #276

**Closed as completed by codeperfectplus** 2020-10-11 10:03 UTC
Labels: good first issue, hacktoberfest
