### ISSUE TITLE
Hamiltonian Cycle | Graph | C++

### ISSUE THREAD

**Issue by harshitgupta2000** [Py-Contributors/AlgorithmsAndDataStructure#586] opened 2020-10-05 05:11 UTC
## **`Title`** -

**what will change** -

### -

Please add/delete options that are not relevant.

 Adding New Code
 Improving Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by SSKale1** [comment] 2020-10-05 06:13
Please only mention a single Programming language per issue.

**Comment by SSKale1** [comment] 2020-10-05 06:17
Duplicate of Issue #89 . Closing Issue.

**Closed as completed by SSKale1** 2020-10-05 06:17 UTC
Labels: good first issue, hacktoberfest, duplicate issue
