### ISSUE TITLE
HeapSort | Sorting Algorithms | C++

### ISSUE THREAD

**Issue by sayashraaj** [Py-Contributors/AlgorithmsAndDataStructure#394] opened 2020-10-01 16:54 UTC
## **`Title`** - HeapSort algorithm implementation in C++

**what will change** - HeapSort algorithm script will be added

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by sayashraaj** [comment] 2020-10-01 16:54
@SSKale1 opening new issue, please assign to me

**Comment by ExpressHermes** [comment] 2020-10-01 17:21
duplicate of #5

**Closed as completed by ExpressHermes** 2020-10-01 17:21 UTC
